import { createClient } from '@/lib/supabase/server';
import { NextRequest, NextResponse } from 'next/server';
import type { ProposalStatus, ProposalCurrency, EventType } from '@/types/database';

// ─── POST /api/proposals ──────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  try {
    const supabase = await createClient();

    // Auth check
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();
    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Parse body
    const body = await req.json();
    const {
      customer_id,
      title,
      destination,
      travel_date_from,
      travel_date_to,
      num_adults,
      num_children,
      currency,
      message_to_customer,
      notes,
    } = body;

    // Validate required fields
    if (!customer_id || typeof customer_id !== 'string') {
      return NextResponse.json({ error: 'customer_id is required' }, { status: 400 });
    }
    if (!title || typeof title !== 'string' || title.trim().length < 3) {
      return NextResponse.json(
        { error: 'title must be at least 3 characters' },
        { status: 400 },
      );
    }

    // Insert proposal — cast to any to avoid TS narrowing issues with generated DB types
    // (share_token is generated by DB trigger, not required in Insert payload)
    const proposalInsert = {
      customer_id: customer_id as string,
      title: (title as string).trim(),
      destination: (destination as string | null) ?? null,
      travel_date_from: (travel_date_from as string | null) ?? null,
      travel_date_to: (travel_date_to as string | null) ?? null,
      num_adults: (num_adults as number) ?? 2,
      num_children: (num_children as number) ?? 0,
      currency: ((currency as ProposalCurrency) ?? 'INR') as ProposalCurrency,
      message_to_customer: (message_to_customer as string | null) ?? null,
      notes: (notes as string | null) ?? null,
      status: 'draft' as ProposalStatus,
      created_by: user.email ?? user.id,
    };

    const { data: newProposal, error: insertError } = await supabase
      .from('proposals')
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      .insert(proposalInsert as any)
      .select()
      .single();

    if (insertError || !newProposal) {
      console.error('[proposals/POST] insert error:', insertError);
      return NextResponse.json(
        { error: insertError?.message ?? 'Failed to create proposal' },
        { status: 500 },
      );
    }

    // Create empty proposal_pricing row
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const { error: pricingError } = await supabase.from('proposal_pricing').insert({
      proposal_id: (newProposal as { id: string }).id,
      base_price_per_person: 0,
      child_price_per_person: 0,
      group_discount_pct: 0,
      gst_pct: 5,
      apply_gst: true,
      total_price: 0,
      inclusions: [
        'Accommodation (as per itinerary)',
        'Daily breakfast & dinner',
        'All transfers & sightseeing',
        'Experienced local guide',
        'All entry fees & permits',
        'GST & service charges',
      ],
      exclusions: [
        'Airfare / train tickets',
        'Lunch & personal expenses',
        'Travel insurance',
        'Tips & gratuities',
        'Anything not mentioned in inclusions',
      ],
      payment_terms:
        '30% advance at booking. Balance 15 days before travel date.',
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any);

    if (pricingError) {
      // Non-fatal — proposal was created; log but don't fail
      console.error('[proposals/POST] pricing insert error:', pricingError);
    }

    // Log event
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const { error: eventError } = await supabase.from('proposal_events').insert({
      proposal_id: (newProposal as { id: string }).id,
      event: 'created' as EventType,
      actor: user.email ?? user.id,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any);

    if (eventError) {
      console.error('[proposals/POST] event log error:', eventError);
    }

    return NextResponse.json({ success: true, proposal: newProposal }, { status: 201 });
  } catch (err: unknown) {
    console.error('[proposals/POST] unexpected error:', err);
    return NextResponse.json(
      {
        error: err instanceof Error ? err.message : 'Internal server error',
      },
      { status: 500 },
    );
  }
}
